baseURL = "localhost"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10
author = "Pa1NarK"
disableMermaid = false
enableRobotsTXT = true

[minify]
minifyOutput = true

[permalinks]
posts = "/posts/:year/:month/:title/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[languages]
[languages.en]
title = "Pa1NarK"
keywords = "pixincreate, pavan, pavana, pix, portfolio, blog, resume, homepage"
copyright = 'CC0 1.0 Universal'

[languages.en.params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

homeSubtitle = "An 8-bit dev converting coffee to code!"
subtitle = "pixincreate portfolio"
enableSharingButtons = true
canonifyURLs = true
description = "pixincreate's website"
keywords = "blog, homepage, portfolio, resume"
images = [""]
justifyContent = true
rss = true

custom_css = ["css/styles.css"]

[[languages.en.params.social]]
name = "github"
url = "https://github.com/pixincreate"

[[languages.en.params.social]]
name = "linkedin"
url = "https://linkedin.com/pavananarayanak"

[[languages.en.params.social]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/12320089/theycallmepix"

[params.portrait]
path = "img/avatar.png"
alt = "Avatar"
maxWidth = "125px"

[languages.en.params.logo]
logoMark = "$"
logoText = ["pixincreate.", "PiX.", "Pavan.", "Pa1NarK."]
logoHomeLink = "/"
logoCursorDisabled = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 1

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 1

[[menu.main]]
identifier = "youtube"
name = "YouTube"
url = "youtube/"

[[menu.main]]
identifier = "work"
name = "Work"
url = "work/"
weight = 2

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false
[privacy.instagram]
disable = true
simple = true
[privacy.twitter]
disable = true
enableDNT = false
simple = false
[privacy.vimeo]
disable = true
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true
